### ISSUE TITLE
Figura 1 y 2

### ISSUE THREAD

**Issue by forero** [povedaruiz/MACH#3]
En la Figura 1 y 2 todas las lineas son iguales y no se sabe a cual corresponde cual concentracion.
Se deberia reducir el numero de lineas a 4 y hacer que cada una tenga o un tipo de linea diferente o un grosor diferente para que se puedan diferenciar.

**Comment by povedaruiz** [comment]
arreglado en https://github.com/povedaruiz/MACH/commit/3ae06848ace6f0f13890a4678771e2fe9f25e901
