### ISSUE TITLE
Figura 4

### ISSUE THREAD

**Issue by forero** [povedaruiz/MACH#5]
Varias cosas para cambiar en la Figura 4.
* Aumentar el tamano de la fuenta para que sea como la Figura 3.
* Que los labels de cada curva esten en fuente romana y no en italica.
* Que el label mass sea "Our method".
* Que \xi pase a ser \langle|D|\rangle

**Comment by povedaruiz** [comment]
Resuelto en https://github.com/povedaruiz/MACH/commit/24628f00c3cb7eb84f6a13cefcca31995bd08469
