### ISSUE TITLE
Figura 5.

### ISSUE THREAD

**Issue by forero** [povedaruiz/MACH#6]
Varias cosas para cambiar en la Figura 5.
* Que sean tres figuras independientes y no las tres un panel unico.
* Que los ejes no esten marcados como XXX Method sino como Concentration (XXX Method).
* Que Mass Method se convierta en "Our Method".

**Comment by povedaruiz** [comment]
resuelto en https://github.com/povedaruiz/MACH/commit/24628f00c3cb7eb84f6a13cefcca31995bd08469
